param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\common\bin\cspybat" -f "D:\development\st\stm32\src_code\stm32cubef1_development\en.stm32cubef1\STM32Cube_FW_F1_V1.4.0\Projects\STM32F103C8T6_MINI_BOARD\Applications\USB_Device\HID_Standalone\EWARM\settings\USBD_HID.STM32F103RB_Nucleo.general.xcl" --backend -f "D:\development\st\stm32\src_code\stm32cubef1_development\en.stm32cubef1\STM32Cube_FW_F1_V1.4.0\Projects\STM32F103C8T6_MINI_BOARD\Applications\USB_Device\HID_Standalone\EWARM\settings\USBD_HID.STM32F103RB_Nucleo.driver.xcl" 
}
else
{
& "C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\common\bin\cspybat" -f "D:\development\st\stm32\src_code\stm32cubef1_development\en.stm32cubef1\STM32Cube_FW_F1_V1.4.0\Projects\STM32F103C8T6_MINI_BOARD\Applications\USB_Device\HID_Standalone\EWARM\settings\USBD_HID.STM32F103RB_Nucleo.general.xcl" --debug_file=$debugfile --backend -f "D:\development\st\stm32\src_code\stm32cubef1_development\en.stm32cubef1\STM32Cube_FW_F1_V1.4.0\Projects\STM32F103C8T6_MINI_BOARD\Applications\USB_Device\HID_Standalone\EWARM\settings\USBD_HID.STM32F103RB_Nucleo.driver.xcl" 
}
